language: ruby
rvm:
  - 2.1.0
script: bundle exec jekyll build
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.net#hackerspace-silesia
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
