language: ruby
env:
  global:
    - secure: "SAQK6BwFHP1fdBdGQWUP5Y34USuWqEh9k3i3N3F4ZPyrDHj0oXsq9Mw0RKwFmazKexzbd8P0YGiaXnxlfMhYWNRMVsZLWFViqjXnmzZyZa8fkcwWxIimcUPeYNaDMb0Q684r6+rpNNy8OyZtsPZR26jvg4vWL6KnLDfSOgmJnU0="
rvm:
  - 2.1.0
script: bundle exec jekyll build
branches:
  only:
    - jekyll
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - git checkout master
  - rsync -avzh _site/ ./
  - git add .
  - echo "$GIT_NAME $GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git config --global github.token "$GH_TOKEN"
  - git commit -m 'New site version' 
  - git remote set-url origin git@github.com:hackerspace-silesia/hackerspace-silesia.github.io.git
  - git push origin master
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.net#hackerspace-silesia
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
